apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __CI_PROJECT_NAME__-pv-claim
  labels:
    app: __CI_PROJECT_NAME__-app
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi-storagenode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

